### ISSUE TITLE
Error when attemp to use the programme

### ISSUE THREAD

**Issue by MinePlugins** [jblance/mpp-solar#1]
I got this error when I use your program:

ERROR: test_getfullstatus (__main__.test_mpputils)
Should return full status
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_mpputils.py", line 65, in test_getfullstatus
    status = mp.getFullStatus()
  File "/usr/local/lib/python2.7/dist-packages/mpp_solar-0.1.3-py2.7.egg/mppsolar/mpputils.py", line 64, in getFullStatus
    data = self.mp.getResponseDict("Q1")
AttributeError: mppCommands instance has no attribute 'getResponseDict'

**Comment by jblance** [comment]
Sorry I started a refactor and the code wasnt in a stable state

Should work now (though test coverage is now way down)
