### ISSUE TITLE
Catch duplicate sections error in config file and warn the user 

### ISSUE THREAD

**Issue by jblance** [jblance/mpp-solar#102]
INFO:root:Solar Device Command Utility, version: 0.7.40, recent changes: add mqtt_topic option and json_mqtt output
Traceback (most recent call last):
  File "/usr/local/bin/mpp-solar", line 11, in <module>
    load_entry_point('mpp-solar', 'console_scripts', 'mpp-solar')()
  File "/home/pi/src/mpp-solar/mppsolar/_init_.py", line 253, in main
    config.read(args.configfile)
  File "/usr/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib/python3.7/configparser.py", line 1065, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/etc/mpp-solar/mpp-solar.conf' [line 38]: section 'Hass_Sensors' already exists

**Comment by jblance** [comment]
maybe also missing [setup] and required fields??

**Comment by jblance** [comment]
added in 0.7.59
