### ISSUE TITLE
Firm 8.X

### ISSUE THREAD

**Issue by jouking** [jblance/mpp-solar#144]
I have a jkbms that I bought recently and it has the firm 8.X. Is it possible to make any modifications so that your program works with this firmware?

Thanks.

**Comment by jouking** [comment]
Tried to launch jkbms, and I get always "IndexError: list index out of range", using -P JK02 and -P JK04:

```
root@raspberrypi:/home/pi# jkbms -p C8:47:XX:XX:XX:XX -P JK02 -c getCellData
Traceback (most recent call last):
  File "/usr/local/bin/jkbms", line 33, in <module>
    sys.exit(load_entry_point('mpp-solar', 'console_scripts', 'jkbms')())
  File "/home/pi/src/mpp-solar/mppsolar/__init__.py", line 408, in main
    results = _device.run_command(command=_command)
  File "/home/pi/src/mpp-solar/mppsolar/devices/device.py", line 313, in run_command
    command_defn=self._protocol.get_command_defn(command),
  File "/home/pi/src/mpp-solar/mppsolar/io/jkbleio.py", line 34, in send_and_receive
    response = self.ble_get_data(full_command)
  File "/home/pi/src/mpp-solar/mppsolar/io/jkbleio.py", line 91, in ble_get_data
    characteristicRead = serviceNotify.getCharacteristics(characteristicReadUuid)[0]
IndexError: list index out of range
```

Seems to have different firmware responses. Tried a lot of things, but any advice will help for sure.

Best regards!

**Comment by jblance** [comment]
Can you add the debug flag `-D` and post the output

**Comment by w0vka** [comment]
same here...
here is my debug output:
`
root@DietPi:~# jkbms -p C8:47:8C:xx:xx:xx -c getInfo -D
2021-11-01 12:03:01,463:INFO:__init__:main@236: Solar Device Command Utility, version: 0.7.76, remove brackets in ved protocol
2021-11-01 12:03:01,464:INFO:__init__:main@340: Creating device "unnamed" (type: "jkbms") on port "C8:47:8C:xx:xx:xx (porttype=None)" using protocol "JK04"
2021-11-01 12:03:01,468:DEBUG:__init__:main@343: device_class <class 'mppsolar.devices.jkbms.jkbms'>
2021-11-01 12:03:01,469:DEBUG:device:__init__@31: __init__ args ()
2021-11-01 12:03:01,469:DEBUG:device:__init__@32: __init__ kwargs {'name': 'unnamed', 'port': 'C8:47:8C:xx:xx:xx', 'protocol': 'JK04', 'baud': 2400, 'porttype': None, 'mqtt_broker': 'localhost', 'mqtt_port': 1883, 'mqtt_user': None, 'mqtt_pass': None}
2021-11-01 12:03:01,469:DEBUG:device:get_port_type@71: port matches jkble ':'
2021-11-01 12:03:01,470:INFO:device:set_port@154: Using jkbleio for communications
2021-11-01 12:03:01,553:DEBUG:device:set_protocol@96: Protocol JK04
2021-11-01 12:03:01,581:DEBUG:device:__init__@36: __init__ name unnamed, port <mppsolar.io.jkbleio.JkBleIO object at 0x768d31b0>, protocol <mppsolar.protocols.jk04.jk04 object at 0x768d3970>
2021-11-01 12:03:01,581:DEBUG:__init__:main@390: Commands [(<mppsolar.devices.jkbms.jkbms object at 0x768d3130>, 'getInfo', 'getInfo', 'screen', None, None)]
2021-11-01 12:03:01,582:INFO:__init__:main@395: Looping 1 commands
2021-11-01 12:03:01,582:INFO:__init__:main@406: Getting results from device: jkbms device - name: unnamed, port: <mppsolar.io.jkbleio.JkBleIO object at 0x768d31b0>, protocol: <mppsolar.protocols.jk04.jk04 object at 0x768d3970> for command: getInfo, tag: getInfo, outputs: screen
2021-11-01 12:03:01,582:INFO:device:run_command@270: Running command getInfo
2021-11-01 12:03:01,583:INFO:jkabstractprotocol:get_full_command@70: Using protocol b'JK04' with 2 commands
2021-11-01 12:03:01,583:DEBUG:jkabstractprotocol:get_command_defn@95: get_command_defn for: getInfo
2021-11-01 12:03:01,583:DEBUG:abstractprotocol:get_command_defn@42: Processing command 'getInfo'
2021-11-01 12:03:01,583:DEBUG:abstractprotocol:get_command_defn@44: Found command getInfo in protocol b'JK04'
2021-11-01 12:03:01,584:DEBUG:jkabstractprotocol:get_full_command@74: self._command = getInfo, self._command_defn = {'name': 'getInfo', 'command_code': '97', 'record_type': '3', 'description': 'BLE Device Information inquiry', 'help': ' -- queries the ble device information', 'type': 'QUERY', 'response_type': 'POSITIONAL', 'response': [['Hex2Str', 4, 'Header', ''], ['Hex2Str', 1, 'Record Type', ''], ['Hex2Int', 1, 'Record Counter', ''], ['Hex2Ascii', 10, 'Device Model', ''], ['Hex2Ascii', 10, 'Hardware Version', ''], ['Hex2Ascii', 10, 'Software Version', ''], ['discard', 10, '', ''], ['Hex2Ascii', 16, 'Device Name', ''], ['Hex2Ascii', 10, 'Device Passcode', ''], ['Hex2Ascii', 14, 'Manufacturing Date', ''], ['Hex2Ascii', 14, 'Serial Number', ''], ['Hex2Ascii', 16, 'User Data', ''], ['Hex2Ascii', 16, 'Settings Passcode?', ''], ['discard', 672, 'unknown', '']], 'test_responses': [b'U\xaa\xeb\x90\x03\xf1JK-B2A24S\x00\x00\x00\x00\x00\x00\x003.0\x00\x00\x00\x00\x003.2.3\x00\x00\x00\x08vE\x00\x04\x00\x00\x00Power Wall 1\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc2', b'U\xaa\xeb\x90\x03\xb5JK-BD6A20S10P\x00\x00\x004.0\x00\x00\x00\x00\x004.1.7\x00\x00\x00T\x1d\x16\x00\x04\x00\x00\x00Nothing JK1\x00\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00200708\x00\x002006284075\x00\x00\x00\x00\x00\x00Input Userdata\x00\x00123456\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc4']}
2021-11-01 12:03:01,584:DEBUG:jkabstractprotocol:get_full_command@85: cmd with SOR: bytearray(b'\xaaU\x90\xeb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2021-11-01 12:03:01,585:DEBUG:jkabstractprotocol:get_full_command@88: cmd with command code: bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2021-11-01 12:03:01,585:DEBUG:jkabstractprotocol:get_full_command@90: cmd with crc: bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11')
2021-11-01 12:03:01,585:INFO:device:run_command@296: full command bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11') for command getInfo
2021-11-01 12:03:01,586:DEBUG:jkabstractprotocol:get_command_defn@95: get_command_defn for: getInfo
2021-11-01 12:03:01,586:DEBUG:abstractprotocol:get_command_defn@42: Processing command 'getInfo'
2021-11-01 12:03:01,586:DEBUG:abstractprotocol:get_command_defn@44: Found command getInfo in protocol b'JK04'
2021-11-01 12:03:01,586:INFO:jkabstractprotocol:get_full_command@70: Using protocol b'JK04' with 2 commands
2021-11-01 12:03:01,586:DEBUG:jkabstractprotocol:get_command_defn@95: get_command_defn for: getInfo
2021-11-01 12:03:01,587:DEBUG:abstractprotocol:get_command_defn@42: Processing command 'getInfo'
2021-11-01 12:03:01,587:DEBUG:abstractprotocol:get_command_defn@44: Found command getInfo in protocol b'JK04'
2021-11-01 12:03:01,587:DEBUG:jkabstractprotocol:get_full_command@74: self._command = getInfo, self._command_defn = {'name': 'getInfo', 'command_code': '97', 'record_type': '3', 'description': 'BLE Device Information inquiry', 'help': ' -- queries the ble device information', 'type': 'QUERY', 'response_type': 'POSITIONAL', 'response': [['Hex2Str', 4, 'Header', ''], ['Hex2Str', 1, 'Record Type', ''], ['Hex2Int', 1, 'Record Counter', ''], ['Hex2Ascii', 10, 'Device Model', ''], ['Hex2Ascii', 10, 'Hardware Version', ''], ['Hex2Ascii', 10, 'Software Version', ''], ['discard', 10, '', ''], ['Hex2Ascii', 16, 'Device Name', ''], ['Hex2Ascii', 10, 'Device Passcode', ''], ['Hex2Ascii', 14, 'Manufacturing Date', ''], ['Hex2Ascii', 14, 'Serial Number', ''], ['Hex2Ascii', 16, 'User Data', ''], ['Hex2Ascii', 16, 'Settings Passcode?', ''], ['discard', 672, 'unknown', '']], 'test_responses': [b'U\xaa\xeb\x90\x03\xf1JK-B2A24S\x00\x00\x00\x00\x00\x00\x003.0\x00\x00\x00\x00\x003.2.3\x00\x00\x00\x08vE\x00\x04\x00\x00\x00Power Wall 1\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc2', b'U\xaa\xeb\x90\x03\xb5JK-BD6A20S10P\x00\x00\x004.0\x00\x00\x00\x00\x004.1.7\x00\x00\x00T\x1d\x16\x00\x04\x00\x00\x00Nothing JK1\x00\x00\x00\x00\x001234\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00200708\x00\x002006284075\x00\x00\x00\x00\x00\x00Input Userdata\x00\x00123456\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc4']}
2021-11-01 12:03:01,588:DEBUG:jkabstractprotocol:get_full_command@85: cmd with SOR: bytearray(b'\xaaU\x90\xeb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2021-11-01 12:03:01,588:DEBUG:jkabstractprotocol:get_full_command@88: cmd with command code: bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2021-11-01 12:03:01,588:DEBUG:jkabstractprotocol:get_full_command@90: cmd with crc: bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11')
2021-11-01 12:03:01,589:INFO:jkbleio:send_and_receive@26: full command bytearray(b'\xaaU\x90\xeb\x97\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11') for command getInfo
2021-11-01 12:03:01,589:DEBUG:jkabstractprotocol:get_command_defn@95: get_command_defn for: getInfo
2021-11-01 12:03:01,589:DEBUG:abstractprotocol:get_command_defn@42: Processing command 'getInfo'
2021-11-01 12:03:01,590:DEBUG:abstractprotocol:get_command_defn@44: Found command getInfo in protocol b'JK04'
2021-11-01 12:03:01,590:DEBUG:jkbleio:send_and_receive@30: expected record type 3 for command getInfo
2021-11-01 12:03:01,590:INFO:jkbleio:ble_connect@54: Attempting to connect to C8:47:8C:xx:xx:xx
2021-11-01 12:03:02,442:INFO:jkbleio:ble_get_data@82: Connected to b''
Traceback (most recent call last):
  File "/usr/local/bin/jkbms", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/mppsolar/__init__.py", line 408, in main
    results = _device.run_command(command=_command)
  File "/usr/local/lib/python3.7/dist-packages/mppsolar/devices/device.py", line 313, in run_command
    command_defn=self._protocol.get_command_defn(command),
  File "/usr/local/lib/python3.7/dist-packages/mppsolar/io/jkbleio.py", line 34, in send_and_receive
    response = self.ble_get_data(full_command)
  File "/usr/local/lib/python3.7/dist-packages/mppsolar/io/jkbleio.py", line 91, in ble_get_data
    characteristicRead = serviceNotify.getCharacteristics(characteristicReadUuid)[0]
IndexError: list index out of range`

Would be very useful to run your program with this firmware.

Best regards

**Comment by syssi** [comment]
This hardware version is supported now. The issue can be closed.
