### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by volkerjaenisch** [jblance/mpp-solar#21]
Dear John!

Rebased my code and noticed that a test is failing:

======================================================================
ERROR: test_bulk_commands (tests.test_mppinverter.test_mppinverter)
Test all query commands
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/volker/workspace/PYTHON/test_mpp/mpp-solar/tests/test_mppinverter.py", line 114, in test_bulk_commands
    command = inverter.execute(cmd)
  File "/home/volker/workspace/PYTHON/test_mpp/mpp-solar/mppsolar/mppinverter.py", line 348, in execute
    return self._doTestCommand(command)
  File "/home/volker/workspace/PYTHON/test_mpp/mpp-solar/mppsolar/mppinverter.py", line 248, in _doTestCommand
    command.setByteResponse(command.getTestByteResponse())
  File "/home/volker/workspace/PYTHON/test_mpp/mpp-solar/mppsolar/mppcommand.py", line 139, in setByteResponse
    self.response_dict = self.getResponseDict()
  File "/home/volker/workspace/PYTHON/test_mpp/mpp-solar/mppsolar/mppcommand.py", line 446, in getResponseDict
    msgs[key] = [resp_format[2][result], '']
KeyError: '139'

----------------------------------------------------------------------
Ran 22 tests in 2.564s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=22 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=22 errors=1 failures=0>

**Comment by jblance** [comment]
corrected 2 test responses, tests currently passing on travis
