### ISSUE TITLE
Not working after I updated?

### ISSUE THREAD

**Issue by axyaxyfr** [jblance/mpp-solar#262]
I just updated to the latest version, and now I get this:

Traceback (most recent call last):
  File "/home/ps/.local/bin/jkbms", line 8, in <module>
    sys.exit(main())
  File "/home/ps/.local/lib/python3.9/site-packages/mppsolar/__init__.py", line 408, in main
    results = _device.run_command(command=_command)
  File "/home/ps/.local/lib/python3.9/site-packages/mppsolar/devices/device.py", line 309, in run_command
    raw_response = self._port.send_and_receive(
  File "/home/ps/.local/lib/python3.9/site-packages/mppsolar/io/jkbleio.py", line 34, in send_and_receive
    response = self.ble_get_data(full_command)
  File "/home/ps/.local/lib/python3.9/site-packages/mppsolar/io/jkbleio.py", line 91, in ble_get_data
    characteristicRead = serviceNotify.getCharacteristics(characteristicReadUuid)[0]
IndexError: list index out of range

My config looks like this:

[SETUP]
# Number of seconds to pause between loops of processing the sections
# i.e. the pause at the end of an entire run through the config file
# default is 60
pause=60
# ipaddress or hostname of the mqtt broker, default is 'localhost'
mqtt_broker=10.100.0.42
# mqtt broker port number, default is 1883
mqtt_port=1883
# username and password (if required) for mqtt broker, default to None and not used unless defined
mqtt_user=*
mqtt_pass=*

[JKBMS#1]
type=jkbms
protocol=JK02
port=C8:47:8C:F7:88:FE 
command=getCellData
tag=22018
outputs=mqtt

Any suggestions?

**Comment by axyaxyfr** [comment]
Sorry about this. I reinstalled everything again, and now it works.
