### ISSUE TITLE
Trying to use powermon over serial but no luck so far

### ISSUE THREAD

**Issue by hasselk** [jblance/mpp-solar#398]
Hello There,
Is powermon in the moment even working over serial connections or ist it only working with test connections?

I cant find anywhere that the Serial Port connect Funtion is even called. But that does not have to mean too much ;)

but i then only get an error on linux and windows with the current release:
2023-09-08 12:16:59,505:DEBUG:serialport:send_and_receive@57: port None
2023-09-08 12:16:59,505:ERROR:serialport:send_and_receive@59: Port not available

Testconfig used:
`device:
  name: VMIII-5k
  id: VMIII-5k
  model: VMIII-5k
  manufacturer: Masterpower
  port:
    type: serial
    path: "COM5"
    baud: 2400
    protocol: PI30

commands:
    - command: QPIGS #Must be in the protocol command list
      #type: poll
      #device: VMIII-5k
      outputs:
        - type: screen
          format: table
#        - type: screen
#          #device: VMIII-5k
#          format: 
#            type: hass
#            entity_id_prefix: VMIII-5k
#            discovery_prefix: home
`
do i have to do something differently?
Thats for checking.

**Comment by jblance** [comment]
I'm not sure it works on windows (haven't ever tried to get it working) for
Linux the path will not be com5, but more like /dev/ttyUSB0 etc.
Will need more details on your physical setup and the output of a debug run
to help more

Mppsolar might be easier place to start (especially as powermon is wip)

**Comment by hasselk** [comment]
MPP-solar is working. But id like to control the Inverter thats why i need Powermon running :-)
i got the Same error on linux with  /dev/ttyUSB0.
Let me try the linux container with debug output and i will post it here. Thanks a lot

**Comment by jblance** [comment]
Post the mppsolar command and that will help translate to powermon config

**Comment by hasselk** [comment]
its all running in the Docker container, just built it myself because the official container seems to be missing the Docker startup Command.
by the way is there an easy way in mpp-solar to change the mqtt topic it is using without changing the code itself?

working mpp-solar config:
`[SETUP]
pause=1
mqtt_broker=hass.xxxx.xxx
mqtttopic=home
#mqtt_user=
#mqtt_pass=

[VMIII-5k]
port=/dev/ttyUSB0
type=mppsolar
protocol=PI30
 #PI30:037:VMIII-5000
command=QPIGS
#QFLAG
#,QMOD
#,QPIWS,QOPM,QFLAG,QMOD
tag=mpp
outputs=screen,hass_mqtt`

powermon_config on linux:
`device:
  id: VMIII-5k
  model: VMIII-5k
  manufacturer: Masterpower
  port:
    type: serial
    path: /dev/ttyUSB0
    protocol: PI30

commands:
- command: QPIGS #Must be in the protocol command list
  #  type: poll
  outputs:
    - type: screen
      format: table
    #- type: mqtt
    #format:  
    # type: hass
    # entity_id_prefix: VMIII-5k 
    # discovery_prefix: home`

powermon_debug_output:
`2023-09-08 10:52:10,578:INFO:__init__:main@114: Power Device Monitoring Utility, version: 0.16.10
2023-09-08 10:52:10,578:INFO:__init__:main@120: Using config file: powermon.yaml
2023-09-08 10:52:10,584:INFO:__init__:main@130: config=BaseConfig(device=DeviceConfig(name=None, id='VMIII-5k', model='VMIII-5k', manufacturer='Masterpower', port=SerialPortConfig(type='serial', path='/dev/ttyUSB0', baud=None, protocol='PI30')), commands=[CommandConfig(command='QPIGS', type=None, trigger=None, outputs=[OutputConfig(type='screen', format='table')])], mqttbroker=MQTTConfig(name='hass.h725k.de', port=1883, username=None, password=None), api=None, daemon=None, debuglevel='10', loop=None)
2023-09-08 10:52:10,585:INFO:__init__:main@145: config: {'device': {'id': 'VMIII-5k', 'model': 'VMIII-5k', 'manufacturer': 'Masterpower', 'port': {'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}}, 'commands': [{'command': 'QPIGS', 'outputs': [{'type': 'screen', 'format': 'table'}]}], 'mqttbroker': {'name': 'hass.h725k.de', 'port': 1883, 'username': None, 'password': None}, 'debuglevel': 10}
2023-09-08 10:52:10,585:DEBUG:__init__:getPortFromConfig@12: port_config: {'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}
2023-09-08 10:52:10,585:DEBUG:__init__:getPortFromConfig@22: portType: serial
2023-09-08 10:52:10,585:DEBUG:serialport:fromConfig@20: building serial port. config:{'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}
2023-09-08 10:52:10,585:DEBUG:__init__:get_protocol@21: Protocol PI30
2023-09-08 10:52:10,587:DEBUG:__init__:main@149: Device: unnamed_device, self.identifier='VMIII-5k', self.model='VMIII-5k', self.manufacturer='Masterpower', port: SerialPort: self.path='/dev/ttyUSB0', self.baud=2400, protocol:PI30 protocol handler, self.serialPort=None, self.error=None, commands:[]

2023-09-08 10:52:10,587:DEBUG:__init__:getOutputs@46: processing outputsConfig: [{'type': 'screen', 'format': 'table'}]
2023-09-08 10:52:10,588:DEBUG:__init__:parseOutputConfig@65: parseOutputConfig, config: {'type': 'screen', 'format': 'table'}, topic: None
2023-09-08 10:52:10,588:DEBUG:__init__:parseOutputConfig@87: got dict type outputConfig: {'type': 'screen', 'format': 'table'}
2023-09-08 10:52:10,588:DEBUG:__init__:getFormatfromConfig@25: getFormatfromConfig, formatConfig: table, device: None, topic: None
2023-09-08 10:52:10,588:DEBUG:__init__:getFormatfromConfig@37: getFormatfromConfig, formatType: table
2023-09-08 10:52:10,588:DEBUG:__init__:parseOutputConfig@95: got format: outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 10:52:10,588:DEBUG:__init__:getOutputClass@23: outputType screen
2023-09-08 10:52:10,589:DEBUG:screen:__init__@10: outputConfig: None, formatter: outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 10:52:10,589:DEBUG:__init__:parseOutputConfig@97: got output: Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 10:52:10,589:DEBUG:command:__init__@58: Command: self.name='QPIGS' self.full_command=None, self.type='basic', [_outs='Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)'], last_run='Not yet run', next_run='08 Sep 2023 10:52:10', trigger: every 60 loops togo: 0, self.command_defn=None
2023-09-08 10:52:10,590:DEBUG:abstractprotocol:get_command_defn@86: Processing command 'QPIGS'
2023-09-08 10:52:10,590:DEBUG:abstractprotocol:get_command_defn@88: Found command QPIGS in protocol b'PI30'
2023-09-08 10:52:10,590:INFO:__init__:main@155: Device: unnamed_device, self.identifier='VMIII-5k', self.model='VMIII-5k', self.manufacturer='Masterpower', port: SerialPort: self.path='/dev/ttyUSB0', self.baud=2400, protocol:PI30 protocol handler, self.serialPort=None, self.error=None, commands:[<powermon.commands.command.Command object at 0x7f34d8ee45b0>]
2023-09-08 10:52:10,590:DEBUG:mqttbroker:fromConfig@19: mqttbroker config: {'name': 'hass.h725k.de', 'port': 1883, 'username': None, 'password': None}
2023-09-08 10:52:10,590:INFO:__init__:main@160: MqttBroker name: hass.h725k.de, port: 1883, user: None
2023-09-08 10:52:10,590:DEBUG:daemon:fromConfig@31: daemon config: None
2023-09-08 10:52:10,590:DEBUG:daemon:fromConfig@37: daemon not configured, disabling
2023-09-08 10:52:10,590:DEBUG:daemon:__init__@51: got daemon type: disabled, keepalive: 0
2023-09-08 10:52:10,590:INFO:__init__:main@164: Daemon DISABLED
2023-09-08 10:52:10,590:DEBUG:apicoordinator:fromConfig@17: ApiCoordinator config: None
2023-09-08 10:52:10,590:INFO:apicoordinator:fromConfig@19: No api definition in config
2023-09-08 10:52:10,591:DEBUG:mqttbroker:subscribe@136: Not connected, connecting
2023-09-08 10:52:10,591:DEBUG:mqttbroker:connect@88: Connecting to hass.h725k.de on port 1883
2023-09-08 10:52:10,591:DEBUG:mqttbroker:connect@95: No mqtt authentication used
2023-09-08 10:52:10,597:DEBUG:mqttbroker:on_connect@64: MqttBroker connection returned result: 0 Connection successful
2023-09-08 10:52:11,598:DEBUG:mqttbroker:subscribe@142: Subscribing to topic powermon/adhoc
2023-09-08 10:52:11,599:INFO:__init__:main@168: ApiCoordinator DISABLED
2023-09-08 10:52:11,599:INFO:device:initialize@74: initializing device

-08 10:52:11,599:DEBUG:abstractport:run_command@47: Command Command: self.name='QPIGS' self.full_command=None, self.type='basic', [_outs='Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)'], last_run='Not yet run', next_run='08 Sep 2023 10:52:10', trigger: every 60 loops togo: 0, self.command_defn={'name': 'QPIGS', 'description': 'General Status Parameters inquiry', 'help': ' -- queries the value of various metrics from the Inverter', 'response_type': <ResponseType.INDEXED: 4>, 'response': [[0, 'AC Input Voltage', 'float', 'V', {'icon': 'mdi:transmission-tower-export', 'device-class': 'voltage'}], [1, 'AC Input Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [2, 'AC Output Voltage', 'float', 'V', {'icon': 'mdi:power-plug', 'device-class': 'voltage'}], [3, 'AC Output Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [4, 'AC Output Apparent Power', 'int', 'VA', {'icon': 'mdi:power-plug', 'device-class': 'apparent_power'}], [5, 'AC Output Active Power', 'int', 'W', {'icon': 'mdi:power-plug', 'device-class': 'power', 'state_class': 'measurement'}], [6, 'AC Output Load', 'int', '%', {'icon': 'mdi:brightness-percent'}], [7, 'BUS Voltage', 'int', 'V', {'icon': 'mdi:details', 'device-class': 'voltage'}], [8, 'Battery Voltage', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [9, 'Battery Charging Current', 'int', 'A', {'icon': 'mdi:current-dc', 'device-class': 'current'}], [10, 'Battery Capacity', 'int', '%', {'device-class': 'battery'}], [11, 'Inverter Heat Sink Temperature', 'int', '°C', {'icon': 'mdi:details', 'device-class': 'temperature'}], [12, 'PV Input Current', 'float', 'A', {'icon': 'mdi:solar-power', 'device-class': 'current'}], [13, 'PV Input Voltage', 'float', 'V', {'icon': 'mdi:solar-power', 'device-class': 'voltage'}], [14, 'Battery Voltage from SCC', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [15, 'Battery Discharge Current', 'int', 'A', {'icon': 'mdi:battery-negative', 'device-class': 'current'}], [16, 'Device Status', 'flags', ['Is SBU Priority Version Added', 'Is Configuration Changed', 'Is SCC Firmware Updated', 'Is Load On', 'Is Battery Voltage to Steady While Charging', 'Is Charging On', 'Is SCC Charging On', 'Is AC Charging On']], [17, 'RSV1', 'int', 'A'], [18, 'RSV2', 'int', 'A'], [19, 'PV Input Power', 'int', 'W', {'icon': 'mdi:solar-power', 'device-class': 'power', 'state_class': 'measurement'}], [20, 'Device Status2', 'flags', ['Is Charging to Float', 'Is Switched On', 'Is Reserved']]], 'test_responses': [b'(000.0 00.0 230.0 49.9 0161 0119 003 460 57.50 012 100 0069 0014 103.8 57.45 00000 00110110 00 00 00856 010$\x8c\r']}
2023-09-08 10:52:11,599:INFO:abstractprotocol:get_full_command@63: Using protocol b'PI30' with 45 commands
2023-09-08 10:52:11,599:DEBUG:protocol_helpers:crcPI@313: Calculating CRC for b'QPIGS'
2023-09-08 10:52:11,599:DEBUG:protocol_helpers:crcPI@363: Generated CRC 0xb7 0xa9 0xb7a9
2023-09-08 10:52:11,600:DEBUG:abstractprotocol:get_full_command@69: full command: b'QPIGS\xb7\xa9\r'
2023-09-08 10:52:11,600:DEBUG:result:__init__@18: Result: Result: Command: self.name='QPIGS' self.full_command=b'QPIGS\xb7\xa9\r', self.type='basic', [_outs='Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)'], last_run='08 Sep 2023 10:52:11', next_run='08 Sep 2023 10:53:11', trigger: every 60 loops togo: 0, self.command_defn={'name': 'QPIGS', 'description': 'General Status Parameters inquiry', 'help': ' -- queries the value of various metrics from the Inverter', 'response_type': <ResponseType.INDEXED: 4>, 'response': [[0, 'AC Input Voltage', 'float', 'V', {'icon': 'mdi:transmission-tower-export', 'device-class': 'voltage'}], [1, 'AC Input Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [2, 'AC Output Voltage', 'float', 'V', {'icon': 'mdi:power-plug', 'device-class': 'voltage'}], [3, 'AC Output Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [4, 'AC Output Apparent Power', 'int', 'VA', {'icon': 'mdi:power-plug', 'device-class': 'apparent_power'}], [5, 'AC Output Active Power', 'int', 'W', {'icon': 'mdi:power-plug', 'device-class': 'power', 'state_class': 'measurement'}], [6, 'AC Output Load', 'int', '%', {'icon': 'mdi:brightness-percent'}], [7, 'BUS Voltage', 'int', 'V', {'icon': 'mdi:details', 'device-class': 'voltage'}], [8, 'Battery Voltage', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [9, 'Battery Charging Current', 'int', 'A', {'icon': 'mdi:current-dc', 'device-class': 'current'}], [10, 'Battery Capacity', 'int', '%', {'device-class': 'battery'}], [11, 'Inverter Heat Sink Temperature', 'int', '°C', {'icon': 'mdi:details', 'device-class': 'temperature'}], [12, 'PV Input Current', 'float', 'A', {'icon': 'mdi:solar-power', 'device-class': 'current'}], [13, 'PV Input Voltage', 'float', 'V', {'icon': 'mdi:solar-power', 'device-class': 'voltage'}], [14, 'Battery Voltage from SCC', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [15, 'Battery Discharge Current', 'int', 'A', {'icon': 'mdi:battery-negative', 'device-class': 'current'}], [16, 'Device Status', 'flags', ['Is SBU Priority Version Added', 'Is Configuration Changed', 'Is SCC Firmware Updated', 'Is Load On', 'Is Battery Voltage to Steady While Charging', 'Is Charging On', 'Is SCC Charging On', 'Is AC Charging On']], [17, 'RSV1', 'int', 'A'], [18, 'RSV2', 'int', 'A'], [19, 'PV Input Power', 'int', 'W', {'icon': 'mdi:solar-power', 'device-class': 'power', 'state_class': 'measurement'}], [20, 'Device Status2', 'flags', ['Is Charging to Float', 'Is Switched On', 'Is Reserved']]], 'test_responses': [b'(000.0 00.0 230.0 49.9 0161 0119 003 460 57.50 012 100 0069 0014 103.8 57.45 00000 00110110 00 00 00856 010$\x8c\r']}, self.is_valid=False, self.error=False - self.error_messages=[], self.raw_response=None, self.decoded_responses=None
2023-09-08 10:52:11,600:DEBUG:serialport:send_and_receive@57: port None
2023-09-08 10:52:11,600:ERROR:serialport:send_and_receive@59: Port not available
2023-09-08 10:52:11,600:DEBUG:abstractport:run_command@56: after send_and_receive Result: Command: self.name='QPIGS' self.full_command=b'QPIGS\xb7\xa9\r', self.type='basic', [_outs='Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)'], last_run='08 Sep 2023 10:52:11', next_run='08 Sep 2023 10:53:11', trigger: every 60 loops togo: 0, self.command_defn={'name': 'QPIGS', 'description': 'General Status Parameters inquiry', 'help': ' -- queries the value of various metrics from the Inverter', 'response_type': <ResponseType.INDEXED: 4>, 'response': [[0, 'AC Input Voltage', 'float', 'V', {'icon': 'mdi:transmission-tower-export', 'device-class': 'voltage'}], [1, 'AC Input Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [2, 'AC Output Voltage', 'float', 'V', {'icon': 'mdi:power-plug', 'device-class': 'voltage'}], [3, 'AC Output Frequency', 'float', 'Hz', {'icon': 'mdi:current-ac', 'device-class': 'frequency'}], [4, 'AC Output Apparent Power', 'int', 'VA', {'icon': 'mdi:power-plug', 'device-class': 'apparent_power'}], [5, 'AC Output Active Power', 'int', 'W', {'icon': 'mdi:power-plug', 'device-class': 'power', 'state_class': 'measurement'}], [6, 'AC Output Load', 'int', '%', {'icon': 'mdi:brightness-percent'}], [7, 'BUS Voltage', 'int', 'V', {'icon': 'mdi:details', 'device-class': 'voltage'}], [8, 'Battery Voltage', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [9, 'Battery Charging Current', 'int', 'A', {'icon': 'mdi:current-dc', 'device-class': 'current'}], [10, 'Battery Capacity', 'int', '%', {'device-class': 'battery'}], [11, 'Inverter Heat Sink Temperature', 'int', '°C', {'icon': 'mdi:details', 'device-class': 'temperature'}], [12, 'PV Input Current', 'float', 'A', {'icon': 'mdi:solar-power', 'device-class': 'current'}], [13, 'PV Input Voltage', 'float', 'V', {'icon': 'mdi:solar-power', 'device-class': 'voltage'}], [14, 'Battery Voltage from SCC', 'float', 'V', {'icon': 'mdi:battery-outline', 'device-class': 'voltage'}], [15, 'Battery Discharge Current', 'int', 'A', {'icon': 'mdi:battery-negative', 'device-class': 'current'}], [16, 'Device Status', 'flags', ['Is SBU Priority Version Added', 'Is Configuration Changed', 'Is SCC Firmware Updated', 'Is Load On', 'Is Battery Voltage to Steady While Charging', 'Is Charging On', 'Is SCC Charging On', 'Is AC Charging On']], [17, 'RSV1', 'int', 'A'], [18, 'RSV2', 'int', 'A'], [19, 'PV Input Power', 'int', 'W', {'icon': 'mdi:solar-power', 'device-class': 'power', 'state_class': 'measurement'}], [20, 'Device Status2', 'flags', ['Is Charging to Float', 'Is Switched On', 'Is Reserved']]], 'test_responses': [b'(000.0 00.0 230.0 49.9 0161 0119 003 460 57.50 012 100 0069 0014 103.8 57.45 00000 00110110 00 00 00856 010$\x8c\r']}, self.is_valid=False, self.error=True - self.error_messages=['Serial port not available None'], self.raw_response=None, self.decoded_responses=None
2023-09-08 10:52:11,600:INFO:abstractprotocol:decode@279: result.raw_response passed to decode: None
2023-09-08 10:52:11,600:DEBUG:device:runLoop@98: Using Output: Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 10:52:11,600:INFO:screen:process@16: Using output sender: screen
2023-09-08 10:52:11,600:DEBUG:screen:process@17: formatter: outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 10:52:11,601:INFO:table:format@20: Using output formatter: table
2023-09-08 10:52:11,601:DEBUG:table:format@38: displayData: {'error': ['Command: QPIGS incurred an error or errors during execution or processing', ''], 'error_count': [2, ''], 'error_#0': ['Serial port not available None', ''], 'error_#1': ['failed validity check: response was empty', '']}
2023-09-08 10:52:11,601:DEBUG:table:format@66: width_c=50, line_length=99, width_p=12, width_v=74, width_u=6
2023-09-08 10:52:11,601:DEBUG:table:format@72: width_c=50, line_length=99, width_p=12, width_v=74, width_u=6`

**Comment by jblance** [comment]
It's not seeing the serial port. Have you mapped it to the docker container?

**Comment by hasselk** [comment]
yes its mapped and working in similiar fashion with mpp-solar

**Comment by hasselk** [comment]
serial port in mpp-solar container:
`root@31b1d2ff42e3:/etc/mpp-solar# ls -l /dev/ttyUSB0 
crw-rw-rw- 1 nobody nogroup 188, 0 Sep  8 11:19 /dev/ttyUSB0`

and in the powermon container:
`root@57df08eecfa2:/etc/mpp-solar# ls -l /dev/ttyUSB0 
crw-rw-rw- 1 nobody nogroup 188, 0 Sep  8 11:19 /dev/ttyUSB0`

**Comment by hasselk** [comment]
ok i changed the device.py in powermon like this, because the connect war realy NEVER called and thats the reason the port was uninitializes so = none
which for shure is not the right way todo because i think there is no reconnect logic or anything but now the serial connection works ;) or to say it more correctly it connects to the device
`
    def initialize(self):
        log.info("initializing device")
        self.port.connect()
        return
`

**Comment by hasselk** [comment]
and now for something complitly different ;-)

ive activated now the mqtt output but getting this Error, any Ideas?

`  outputs:
    - type: screen
      format: table
    - type: mqtt
      format:
        type: hass
        entity_id_prefix: VMIII-5k
        discovery_prefix: home
`

`2023-09-08 15:25:40,243:INFO:__init__:main@114: Power Device Monitoring Utility, version: 0.16.10
2023-09-08 15:25:40,243:INFO:__init__:main@120: Using config file: powermon.yaml
2023-09-08 15:25:40,251:INFO:__init__:main@130: config=BaseConfig(device=DeviceConfig(name=None, id='VMIII-5k', model='VMIII-5k', manufacturer='Masterpower', port=SerialPortConfig(type='serial', path='/dev/ttyUSB0', baud=None, protocol='PI30')), commands=[CommandConfig(command='QPIGS', type=None, trigger=None, outputs=[OutputConfig(type='screen', format='table'), OutputConfig(type='mqtt', format=HassFormatConfig(type='hass', tag=None, draw_lines=None, keep_case=None, remove_spaces=None, extra_info=None, excl_filter=None, filter=None, discovery_prefix='home', entity_id_prefix='VMIII-5k'))])], mqttbroker=MQTTConfig(name='hass.h725k.de', port=1883, username=None, password=None), api=None, daemon=None, debuglevel='10', loop=None)
2023-09-08 15:25:40,251:INFO:__init__:main@145: config: {'device': {'id': 'VMIII-5k', 'model': 'VMIII-5k', 'manufacturer': 'Masterpower', 'port': {'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}}, 'commands': [{'command': 'QPIGS', 'outputs': [{'type': 'screen', 'format': 'table'}, {'type': 'mqtt', 'format': {'type': 'hass', 'entity_id_prefix': 'VMIII-5k', 'discovery_prefix': 'home'}}]}], 'mqttbroker': {'name': 'hass.h725k.de', 'port': 1883, 'username': None, 'password': None}, 'debuglevel': 10}
2023-09-08 15:25:40,251:DEBUG:__init__:getPortFromConfig@12: port_config: {'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}
2023-09-08 15:25:40,251:DEBUG:__init__:getPortFromConfig@22: portType: serial
2023-09-08 15:25:40,251:DEBUG:serialport:fromConfig@20: building serial port. config:{'type': 'serial', 'path': '/dev/ttyUSB0', 'protocol': 'PI30'}
2023-09-08 15:25:40,251:DEBUG:__init__:get_protocol@21: Protocol PI30
2023-09-08 15:25:40,253:DEBUG:__init__:main@149: Device: unnamed_device, self.identifier='VMIII-5k', self.model='VMIII-5k', self.manufacturer='Masterpower', port: SerialPort: self.path='/dev/ttyUSB0', self.baud=2400, protocol:PI30 protocol handler, self.serialPort=None, self.error=None, commands:[]
2023-09-08 15:25:40,253:DEBUG:__init__:getOutputs@46: processing outputsConfig: [{'type': 'screen', 'format': 'table'}, {'type': 'mqtt', 'format': {'type': 'hass', 'entity_id_prefix': 'VMIII-5k', 'discovery_prefix': 'home'}}]
2023-09-08 15:25:40,253:DEBUG:__init__:parseOutputConfig@65: parseOutputConfig, config: {'type': 'screen', 'format': 'table'}, topic: None
2023-09-08 15:25:40,254:DEBUG:__init__:parseOutputConfig@87: got dict type outputConfig: {'type': 'screen', 'format': 'table'}
2023-09-08 15:25:40,254:DEBUG:__init__:getFormatfromConfig@25: getFormatfromConfig, formatConfig: table, device: None, topic: None
2023-09-08 15:25:40,254:DEBUG:__init__:getFormatfromConfig@37: getFormatfromConfig, formatType: table
2023-09-08 15:25:40,254:DEBUG:__init__:parseOutputConfig@95: got format: outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 15:25:40,254:DEBUG:__init__:getOutputClass@23: outputType screen
2023-09-08 15:25:40,255:DEBUG:screen:__init__@10: outputConfig: None, formatter: outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 15:25:40,255:DEBUG:__init__:parseOutputConfig@97: got output: Output: Screen, outputs the results to standard out in a table (optionally formatted with line art boxes)
2023-09-08 15:25:40,255:DEBUG:__init__:parseOutputConfig@65: parseOutputConfig, config: {'type': 'mqtt', 'format': {'type': 'hass', 'entity_id_prefix': 'VMIII-5k', 'discovery_prefix': 'home'}}, topic: None
2023-09-08 15:25:40,255:DEBUG:__init__:parseOutputConfig@87: got dict type outputConfig: {'type': 'mqtt', 'format': {'type': 'hass', 'entity_id_prefix': 'VMIII-5k', 'discovery_prefix': 'home'}}
2023-09-08 15:25:40,255:DEBUG:__init__:getFormatfromConfig@25: getFormatfromConfig, formatConfig: {'type': 'hass', 'entity_id_prefix': 'VMIII-5k', 'discovery_prefix': 'home'}, device: None, topic: None
2023-09-08 15:25:40,256:DEBUG:__init__:getFormatfromConfig@37: getFormatfromConfig, formatType: hass
2023-09-08 15:25:40,256:DEBUG:__init__:parseOutputConfig@95: got format: Format: hass
2023-09-08 15:25:40,256:DEBUG:__init__:getOutputClass@23: outputType mqtt
Traceback (most recent call last):
  File "/usr/local/bin/powermon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/powermon/__init__.py", line 152, in main
    command = Command.fromConfig(commandConfig)
  File "/usr/local/lib/python3.10/site-packages/powermon/commands/command.py", line 43, in fromConfig
    outputs = getOutputs(config.get("outputs", ""))
  File "/usr/local/lib/python3.10/site-packages/powermon/outputs/__init__.py", line 55, in getOutputs
    _outputs.append(parseOutputConfig(outputConfig))
  File "/usr/local/lib/python3.10/site-packages/powermon/outputs/__init__.py", line 96, in parseOutputConfig
    _output = getOutputClass(outputType, _format)
  File "/usr/local/lib/python3.10/site-packages/powermon/outputs/__init__.py", line 27, in getOutputClass
    output_class = MQTT(outputConfig, topic, mqtt_broker, _format)
TypeError: Can't instantiate abstract class MQTT with abstract method process
`

**Comment by jblance** [comment]
Looks like a bunch of bugs and unfinished refactoring atm

Will start looking at fixes tonight

**Comment by rossandrews** [comment]
It's very likely this is my fault. I was poking around in the mqtt format to integrate with the API. I switched to making a new format called api_mqtt but may have left mqtt in a bad state. I will investigate.

**Comment by hasselk** [comment]
Hi there, first of all Thanks a lot.

and for the first Problem of the missing _.port.connect()_ for the device, it seems that this was done at one time in the main _init_ and moved to _schedule.py_ in libs with commit [moved port.connect from init to schedule](https://github.com/jblance/mpp-solar/commit/531450626f5f5844d78db37c1a5e67354929ee24#diff-9d24fd77a6e36c8609e900ac06d236443333875f6dc9fbdb048dbbe78c4196ae).

Since schedule.py does not exist any longer, there seems to be no more .port.connect() running. Have not found the commit where the schedule.py got removed yet.

**Comment by oleks85** [comment]
I had the same issues with serial port and mqtt output. I do not have much experience with python, but got fixed all those issues in my fork. There is pull request with fixes #401 .

**Comment by jblance** [comment]
Looks resolved - but note that powermon is undergoing extensive changes so will break and change continuously, use and upgrade with caution
