### ISSUE TITLE
KeyError: 'Y' with PI30

### ISSUE THREAD

**Issue by FastFrank** [jblance/mpp-solar#454]
Hello,

when i put my 5048 in Bypass mode i get this error:

`2024-01-15 15:57:21,777:INFO:device:run_command@50: Running command QMOD
2024-01-15 15:57:21,777:INFO:abstractprotocol:get_full_command@60: Using protocol b'PI30' with 42 commands
2024-01-15 15:57:21,778:INFO:device:run_command@78: full command b'QMODI\xc1\r' for command QMOD
2024-01-15 15:57:22,297:INFO:abstractprotocol:decode@245: response passed to decode: b'(YD\x93\r'
2024-01-15 15:57:22,298:INFO:abstractprotocol:decode@289: Processing response of type DEFAULT
2024-01-15 15:57:22,298:INFO:abstractprotocol:decode@300: Processing DEFAULT type responses
Traceback (most recent call last):
  File "/usr/local/bin/mpp-solar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/mppsolar/__init__.py", line 420, in main
    results = _device.run_command(command=_command)
  File "/usr/local/lib/python3.9/dist-packages/mppsolar/devices/device.py", line 112, in run_command
    decoded_response = self._protocol.decode(raw_response, command)
  File "/usr/local/lib/python3.9/dist-packages/mppsolar/protocols/abstractprotocol.py", line 345, in decode
    msgs[key] = [resp_format[2][result], ""]
KeyError: 'Y'
`

I added:
`                    "Y": "Bypass",
`
in pi30.py on row 493 and now it works fine...

**Comment by jblance** [comment]
great thanks, added to current branch - so should make it in to next version
