### ISSUE TITLE
Deal with situation of inverter returning the command when command isnt supported

### ISSUE THREAD

**Issue by jblance** [jblance/mpp-solar#88]
As noted by @joerghohn the inverter used will respond by returning the command for non-supported commands

eg
```
INFO:device:run_command: full command b'QPGS\xa3\x8c\r' for command QPGS
INFO:AbstractProtocol:decode: response passed to decode: b'QPGS\xa3\x8c\r'
```
Full Info stack
```
INFO:root:Solar Device Command Utility, version: 0.7.42, recent changes: deal with non-numerical result better 
INFO:root:Creating device "FirstInverter" (type: "mppsolar") on port "/dev/ttyUSB0 (porttype=None)" using protocol "PI30"
INFO:device:set_port: Using serialio for communications
INFO:root:Looping 1 commands
INFO:root:Getting results from device: mppsolar device - name: FirstInverter, port: <mppsolar.io.serialio.SerialIO object at 0xb709452c>, protocol: <mppsolar.protocols.pi30.pi30 object at 0xb70947ec> for command: QBOOT, tag: QBOOT, outputs: screen
INFO:device:run_command: Running command QBOOT
INFO:AbstractProtocol:get_full_command: Using protocol b'PI30' with 35 commands
INFO:device:run_command: full command b'QBOOT\x0b\x88\r' for command QBOOT
INFO:AbstractProtocol:decode: response passed to decode: b'QBOOT\x0b\x88\r'
INFO:AbstractProtocol:decode: Processing response of type default
INFO:AbstractProtocol:decode: Processing SEQUENCE type responses
Traceback (most recent call last):
  File "/usr/local/bin/mpp-solar", line 11, in <module>
    load_entry_point('mpp-solar', 'console_scripts', 'mpp-solar')()
  File "/root/src/mpp-solar/mppsolar/__init__.py", line 387, in main
    results = _device.run_command(command=_command)
  File "/root/src/mpp-solar/mppsolar/devices/device.py", line 309, in run_command
    decoded_response = self._protocol.decode(raw_response, command)
  File "/root/src/mpp-solar/mppsolar/protocols/abstractprotocol.py", line 267, in decode
    msgs[key] = [resp_format[2][int(result)], ""]
ValueError: invalid literal for int() with base 10: 'BOOT'
```

**Comment by jblance** [comment]
another example
```
INFO:device:run_command: Running command QPGS0
INFO:AbstractProtocol:get_full_command: Using protocol b'PI30' with 35 commands
INFO:device:run_command: full command b'QPGS0?\xda\r' for command QPGS0
INFO:AbstractProtocol:decode: response passed to decode: b'QPGS0?\xda\r'
```

**Comment by jblance** [comment]
implemented
